tasks:
  - name: terraform
    init: |
      bash ./bin/set_tf_alias
      bash ./bin/install_terraform_cli
      bash ./bin/generate_tfrc_credentials
      bash ./bin/install_aws_credentials
      
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      bash ./bin/set_tf_alias
      bash ./bin/install_aws_cli
      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform